### ISSUE TITLE
Not able to compile in arm7 on version 1.8.3/1.8.2/1.8.1 but it works for 1.8.0

### ISSUE THREAD

**Issue by skulljoi** [awslabs/aws-crt-nodejs#231]
Scanning dependencies of target aws-c-compression
[ 84%] Building C object crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/compression.c.o
[ 84%] Building C object crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman.c.o
[ 84%] Building C object crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman_testing.c.o
/home/gitlab-runner/builds/XXXXXX/0/YYYYYYYY/ZZZZZZZZZZZ/node_modules/aws-crt/crt/aws-c-compression/source/huffman_testing.c:13:10: fatal error: aws/testing/compression/huffman.h: No such file or directory
 #include <aws/testing/compression/huffman.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/build.make:89: crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/source/huffman_testing.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:685: crt/aws-c-compression/CMakeFiles/aws-c-compression.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
ERR! OMG Process terminated: 2
(node:22276) UnhandledPromiseRejectionWarning: Error: Process terminated: 2
    at ChildProcess.<anonymous> (/home/gitlab-runner/builds/XXXXXX/0/YYYYYYYY/ZZZZZZZZZZZ/node_modules/cmake-js/lib/processHelpers.js:29:32)
    at ChildProcess.emit (events.js:314:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
(node:22276) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by bretambrose** [comment]
When you switch between releases are you doing a `git submodule update --init --recursive` as well?

**Comment by skulljoi** [comment]
I am using only npm i aws-crt@VERSION

**Comment by skulljoi** [comment]
> When you switch between releases are you doing a `git submodule update --init --recursive` as well?

node index.js a19urc0vbmuthz-ats.iot.eu-west-1.amazonaws.com 8883

**Comment by bretambrose** [comment]
Looks like aws-c-compression got a structural change recently and somehow test files are in the source but then their header doesn't get packaged (as it shouldn't I think) and its complaining.  Will look into it further.

**Comment by bretambrose** [comment]
With the release of v1.8.4, I've been able to successfully run ```node scripts/build.js``` on an npm installed version of the crt.  Performing the same against v1.8.3 results in the above error, so I feel reasonably confident that this particular issue has been addressed.  That being said, I don't currently have an arm device to test against.  

As an aside, we are hoping to get arm binaries bundled with the npm package in the near-term future.
